name: "构建自定义 OpenWrt 安装程序 ISO"

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '原始URL'
        required: true

jobs:
  build-release:
    name: "构建和发布"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "检出 Git 仓库"
        uses: actions/checkout@v3

      - name: "安装依赖"
        run: |
          sudo apt-get update
          sudo apt-get install -y file curl gzip bzip2 xz-utils p7zip-full unzip qemu-utils tar

      - name: 设置可执行权限
        run: |
          chmod +x "${{ github.workspace }}/custom.sh"
          chmod +x "${{ github.workspace }}/supportFiles/custom/build.sh"

      - name: "构建镜像"
        run: |
          download_url="${{ github.event.inputs.download_url }}"
          ./custom.sh "$download_url"

      - name: 上传压缩后的镜像
        uses: actions/upload-artifact@v4
        with:
          name: custom-installer
          path: output/*.7z